package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestCLITemporaryBuildAndExplicitExport(t *testing.T) {
	sourceRoot, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	cli := filepath.Join(t.TempDir(), "goop")
	if runtime.GOOS == "windows" {
		cli += ".exe"
	}
	build := exec.Command("go", "build", "-o", cli, ".")
	build.Dir = sourceRoot
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build CLI: %v\n%s", err, output)
	}

	project := filepath.Join(t.TempDir(), "zoo")
	if err := os.MkdirAll(project, 0755); err != nil {
		t.Fatal(err)
	}
	files := map[string]string{
		"go.mod": "module example.org/zoo\n\ngo 1.22\n",
		"app.goop": `package main
import "fmt"
public class Dog {
    private name string
    constructor(name string) { this.name = name }
    Speak() string { return this.name + ": Woof!" }
}
func main() { fmt.Println(new Dog("Rex").Speak()) }
`,
		"app_test.go": `package main
import "testing"
func TestGeneratedConstructor(t *testing.T) {
    if got := NewDog("Milo").Speak(); got != "Milo: Woof!" { t.Fatal(got) }
}
`,
	}
	for name, contents := range files {
		if err := os.WriteFile(filepath.Join(project, name), []byte(contents), 0644); err != nil {
			t.Fatal(err)
		}
	}
	invoke := func(args ...string) string {
		t.Helper()
		cmd := exec.Command(cli, args...)
		cmd.Dir = project
		output, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("goop %v failed: %v\n%s", args, err, output)
		}
		return string(output)
	}
	exported := filepath.Join(project, "app_goop.go")
	assertNoExport := func() {
		t.Helper()
		if _, err := os.Stat(exported); !os.IsNotExist(err) {
			t.Fatalf("generated source unexpectedly left in source tree (stat error: %v)", err)
		}
	}
	if output := invoke("run"); !strings.Contains(output, "Rex: Woof!\n") {
		t.Fatalf("run output: %q", output)
	}
	assertNoExport()
	if output := invoke("test"); !strings.Contains(output, "ok") {
		t.Fatalf("test output: %q", output)
	}
	assertNoExport()
	invoke("check")
	assertNoExport()
	invoke("build")
	assertNoExport()
	binary := filepath.Join(project, filepath.Base(project))
	if runtime.GOOS == "windows" {
		binary += ".exe"
	}
	cmd := exec.Command(binary)
	cmd.Dir = project
	if output, err := cmd.CombinedOutput(); err != nil || string(output) != "Rex: Woof!\n" {
		t.Fatalf("built binary: %v: %q", err, output)
	}
	invoke("generate")
	if data, err := os.ReadFile(exported); err != nil || !strings.HasPrefix(string(data), "// Code generated by GoOOP;") {
		t.Fatalf("explicit export missing or malformed: %v", err)
	}
	// Even if an older generated file exists, the temporary overlay must
	// override it, rather than relying on potentially stale source output.
	if output := invoke("run"); !strings.Contains(output, "Rex: Woof!\n") {
		t.Fatal(output)
	}
	invoke("clean")
	assertNoExport()
	// clean must never remove user-authored files with a matching suffix.
	if err := os.WriteFile(exported, []byte("package main\n// user-authored\n"), 0644); err != nil {
		t.Fatal(err)
	}
	invoke("clean")
	if contents, err := os.ReadFile(exported); err != nil || !strings.Contains(string(contents), "user-authored") {
		t.Fatalf("clean deleted a user file: %v", err)
	}
}

func TestOverlayCleanupAfterCompilerFailure(t *testing.T) {
	project := t.TempDir()
	for name, data := range map[string]string{
		"go.mod":   "module example.org/bad\n\ngo 1.22\n",
		"bad.goop": "package main\nclass Broken extends Missing {}\n",
	} {
		if err := os.WriteFile(filepath.Join(project, name), []byte(data), 0644); err != nil {
			t.Fatal(err)
		}
	}
	oldWD, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(project); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(oldWD) })
	scratch := t.TempDir()
	t.Setenv("TMPDIR", scratch)
	_, _, cleanup, err := temporaryOverlay()
	if err == nil || cleanup != nil {
		t.Fatalf("expected compiler error with internal cleanup, got %v", err)
	}
	entries, err := os.ReadDir(scratch)
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), "goop-compile-") {
			t.Fatal(fmt.Sprintf("leaked compiler temp directory: %s", entry.Name()))
		}
	}
	if _, err := os.Stat(filepath.Join(project, "bad_goop.go")); !os.IsNotExist(err) {
		t.Fatalf("compiler failure wrote source file: %v", err)
	}
}

func TestCLICrossFileInheritanceInEphemeralOverlay(t *testing.T) {
	root, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	cli := filepath.Join(t.TempDir(), "goop")
	if runtime.GOOS == "windows" {
		cli += ".exe"
	}
	build := exec.Command("go", "build", "-o", cli, ".")
	build.Dir = root
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build CLI: %v\n%s", err, output)
	}
	project := t.TempDir()
	sources := map[string]string{
		"go.mod": "module example.org/split\n\ngo 1.22\n",
		"parent.goop": `package main
abstract class Parent {
    protected label string = "Base: "
    abstract Speak() string;
    Describe() string { return this.label+this.Speak() }
}`,
		"child.goop": `package main
import "fmt"
class Child extends Parent {
    override Speak() string { return "child" }
}
func main() { fmt.Println(new Child().Describe()) }`,
	}
	for name, contents := range sources {
		if err := os.WriteFile(filepath.Join(project, name), []byte(contents), 0644); err != nil {
			t.Fatal(err)
		}
	}
	invoke := func(args ...string) string {
		t.Helper()
		cmd := exec.Command(cli, args...)
		cmd.Dir = project
		result, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("goop %v: %v\n%s", args, err, result)
		}
		return string(result)
	}
	if got := invoke("run"); got != "Base: child\n" {
		t.Fatalf("got %q", got)
	}
	invoke("check")
	invoke("test")
	for _, filename := range []string{"parent_goop.go", "child_goop.go"} {
		if _, err := os.Stat(filepath.Join(project, filename)); !os.IsNotExist(err) {
			t.Fatalf("generated file leaked: %s (%v)", filename, err)
		}
	}
	invoke("generate", "child.goop")
	if _, err := os.Stat(filepath.Join(project, "child_goop.go")); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(project, "parent_goop.go")); !os.IsNotExist(err) {
		t.Fatalf("unexpected sibling export: %v", err)
	}
	invoke("clean")
}
