package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/el211/GoOOP/internal/compiler"
)

// projectRoot resolves the enclosing Go module. Walking from its root lets
// subdirectory commands compile .goop files imported from sibling packages.
func projectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if info, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil && !info.IsDir() {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("no go.mod found; run goop init or work inside a Go module")
		}
		dir = parent
	}
}

// walkSources visits GoOOP files while respecting Go's nested module boundary.
func walkSources(root string, visit func(string) error) error {
	return filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			if path != root {
				switch entry.Name() {
				case ".git", "vendor", "node_modules", ".idea", ".vscode":
					return filepath.SkipDir
				}
				if strings.HasPrefix(entry.Name(), ".") {
					return filepath.SkipDir
				}
				if info, err := os.Stat(filepath.Join(path, "go.mod")); err == nil && !info.IsDir() {
					return filepath.SkipDir
				}
			}
			return nil
		}
		if !strings.HasSuffix(entry.Name(), ".goop") {
			return nil
		}
		return visit(path)
	})
}

type buildOverlay struct {
	Replace map[string]string `json:"Replace"`
}

// temporaryOverlay writes generated source outside the project, then describes
// virtual *_goop.go files to the standard Go -overlay build flag. The caller
// MUST invoke cleanup, including when a compiler or Go command fails.
func temporaryOverlay() (overlayFile string, count int, cleanup func(), err error) {
	root, err := projectRoot()
	if err != nil {
		return "", 0, nil, err
	}
	tmp, err := os.MkdirTemp("", "goop-compile-")
	if err != nil {
		return "", 0, nil, err
	}
	cleanup = func() { _ = os.RemoveAll(tmp) }
	replacements := make(map[string]string)
	sources := map[string][]byte{}
	err = walkSources(root, func(source string) error {
		data, err := os.ReadFile(source)
		if err != nil {
			return err
		}
		absolute, err := filepath.Abs(source)
		if err != nil {
			return err
		}
		sources[absolute] = data
		return nil
	})
	if err != nil {
		cleanup()
		return "", 0, nil, err
	}
	generatedFiles, err := compiler.CompileFiles(sources)
	if err != nil {
		cleanup()
		return "", 0, nil, err
	}
	paths := make([]string, 0, len(generatedFiles))
	for path := range generatedFiles {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, source := range paths {
		generated := generatedFiles[source]
		count++
		backing := filepath.Join(tmp, fmt.Sprintf("generated-%04d.go", count))
		if err := os.WriteFile(backing, generated, 0600); err != nil {
			cleanup()
			return "", 0, nil, err
		}
		virtual := strings.TrimSuffix(source, ".goop") + "_goop.go"
		replacements[virtual] = backing
	}
	if count == 0 {
		cleanup()
		return "", 0, nil, errors.New("no .goop files found in this module")
	}
	data, err := json.Marshal(buildOverlay{Replace: replacements})
	if err != nil {
		cleanup()
		return "", 0, nil, err
	}
	overlayFile = filepath.Join(tmp, "overlay.json")
	if err := os.WriteFile(overlayFile, data, 0600); err != nil {
		cleanup()
		return "", 0, nil, err
	}
	return overlayFile, count, cleanup, nil
}

// cleanExports removes only GoOOP-authored files corresponding to .goop input.
// Builds and tests have no persistent compiler cache: the OS temp workspace is
// deleted automatically after each command.
func cleanExports() (int, error) {
	root, err := projectRoot()
	if err != nil {
		return 0, err
	}
	removed := 0
	err = walkSources(root, func(source string) error {
		target := strings.TrimSuffix(source, ".goop") + "_goop.go"
		data, err := os.ReadFile(target)
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		if err != nil {
			return err
		}
		if !strings.HasPrefix(string(data), "// Code generated by GoOOP; DO NOT EDIT.") {
			return nil // never delete arbitrary user-written files
		}
		if err := os.Remove(target); err != nil {
			return err
		}
		removed++
		return nil
	})
	return removed, err
}
